// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/Button.vue')['default']
    ClaimCheck: typeof import('./src/components/welcome/ClaimCheck.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LaunchPlan: typeof import('./src/components/home/LaunchPlan.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    MySbts: typeof import('./src/components/home/MySbts.vue')['default']
    NameItem: typeof import('./src/components/NameItem.vue')['default']
    NameScanModal: typeof import('./src/components/NameScanModal.vue')['default']
    RegisterPanel: typeof import('./src/components/register/RegisterPanel.vue')['default']
    RegisterSuccess: typeof import('./src/components/register/RegisterSuccess.vue')['default']
    ReImage: typeof import('./src/components/ReImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TokenSvg: typeof import('./src/components/TokenSvg.vue')['default']
    VList: typeof import('./src/components/VList.vue')['default']
  }
}

export {}
